// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qipsfexznhqqjvrrcuhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpcHNmZXh6bmhxcWp2cnJjdWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzI1OTgsImV4cCI6MjA2NDkwODU5OH0.KfzEiWtUMHS1ACpHrUpdvHymsaJbDSqsJwLu3Rr5fWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);